[build]
  command = "npm run build"
  publish = ".netlify"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "22.12.0"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/__render"
  status = 200
